---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    apt: 
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]
 
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest	
    when: ansible_distribution == "Ubuntu"

# This part will target the CentOS server
  - name: install httpd package on CentOS
    dnf:
      name: httpd
    when: ansible_distribution == "CentOS"

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: add php support for httpd
    dnf:
      name: php
    when: ansible_distribution == "CentOS"
