---

- hosts: all
  become: true
  tasks:

  - name: install apache and php on servers with diff OS distro
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
